spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/car_management_system
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: true

  flyway:
    baseline-on-migrate: true